springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.lybl.loan.management

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    com.lybl.loan.management: INFO


swagger:
  contact-name: Thirumurugan
  contact-mail: omer@Thirumurugan.com
  contact-url: https://Thirumurugan.com
  app-name: Loan Management
  app-description: "Loan Management is a starter kit. This project includes : Spring Boot(2.7.4), Spring Validation, Lombok, Swagger"
  app-version: 2.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
